version: "3.9"

services:
  web:
    image: swarmfr:v2
    ports:
      - "8000:80"
  backend:
    image: swarmexpressbackend:v1
    environment:
      dbhost: "ec2-13-233-149-1.ap-south-1.compute.amazonaws.com"
      dbuser: "jyoti"
      dbpass: "jyoti"
      db: "jyoti"
      port: 3000
    ports:
     - "3000:3000"
      
